services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1

      KAFKA_LISTENERS: SSL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: SSL://127.0.0.1:9092

      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/server.keystore.p12
      KAFKA_SSL_KEYSTORE_FILENAME: server.keystore.p12
      KAFKA_SSL_KEYSTORE_CREDENTIALS: server1.creds
      KAFKA_SSL_KEY_CREDENTIALS: server1.creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: client.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: truststore.creds
      KAFKA_SSL_CLIENT_AUTH: required

      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL: "false"

      KAFKA_SUPER_USERS: "User:CN=localhost;User:CN=admin"

      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SSL:SSL
    volumes:
      - "./certs:/etc/kafka/secrets"
